### ISSUE TITLE
manually reloading exits vim

### ISSUE THREAD

**Issue by nickdesaulniers** [paradoxxxzero/butterfly#10]
stack trace:

```
[E 140228 15:13:30 tcpserver:245] Error in connection callback
    Traceback (most recent call last):
      File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tornado/tcpserver.py", line 243, in _handle_connection
        self.handle_stream(stream, address)
      File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tornado/httpserver.py", line 158, in handle_stream
        self.no_keep_alive, self.xheaders, self.protocol)
      File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tornado/httpserver.py", line 189, in __init__
        self.stream.read_until(b"\r\n\r\n", self._header_callback)
      File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tornado/iostream.py", line 163, in read_until
        self._try_inline_read()
      File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tornado/iostream.py", line 450, in _try_inline_read
        self._maybe_add_error_listener()
      File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tornado/iostream.py", line 600, in _maybe_add_error_listener
        self._add_io_state(ioloop.IOLoop.READ)
      File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tornado/iostream.py", line 630, in _add_io_state
        self.fileno(), self._handle_events, self._state)
      File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tornado/ioloop.py", line 545, in add_handler
        self._impl.register(fd, events | self.ERROR)
      File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tornado/platform/kqueue.py", line 40, in register
        raise IOError("fd %d already registered" % fd)
    IOError: fd 22 already registered
```

**Comment by farhaanbukhsh** [comment]
hey @paradoxxxzero  is this fixed ? If not I would like to work on this.

**Comment by paradoxxxzero** [comment]
I don't think so, but you can try to reproduce with the latest version. And
I'll gladly merge a good PR!
