### ISSUE TITLE
ssl session fail

### ISSUE THREAD

**Issue by iu0v1** [paradoxxxzero/butterfly#60]
Hello. When I try to open session - get 'reset connection' and this error:

```
$ butterfly.server.py --login  --host=10.1.8.122 --port=9999
[W 141120 14:34:01 iostream:1184] SSL Error on 4 ('10.1.8.122', 58746): [Errno 1] _ssl.c:510: error:1407609C:SSL routines:SSL23_GET_CLIENT_HELLO:http request
[E 141120 14:34:01 http1connection:683] Uncaught exception
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/tornado/http1connection.py", line 674, in _server_request_loop
        ret = yield conn.read_response(request_delegate)
      File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 628, in run
        value = future.result()
      File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 109, in result
        raise_exc_info(self._exc_info)
      File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 631, in run
        yielded = self.gen.throw(*sys.exc_info())
      File "/usr/local/lib/python2.7/dist-packages/tornado/http1connection.py", line 165, in _read_message
        io_loop=self.stream.io_loop)
      File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 628, in run
        value = future.result()
      File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 111, in result
        raise self._exception
    SSLError: [Errno 1] _ssl.c:510: error:1407609C:SSL routines:SSL23_GET_CLIENT_HELLO:http request
^CTraceback (most recent call last):
  File "/usr/local/bin/butterfly.server.py", line 258, in <module>
    ioloop.start()
  File "/usr/local/lib/python2.7/dist-packages/tornado/ioloop.py", line 812, in start
    event_pairs = self._impl.poll(poll_timeout)
KeyboardInterrupt
```

```
$ openssl version -a
OpenSSL 1.0.1f 6 Jan 2014
built on: Wed Oct 15 17:43:26 UTC 2014
platform: debian-amd64
options:  bn(64,64) rc4(16x,int) des(idx,cisc,16,int) blowfish(idx) 
compiler: cc -fPIC -DOPENSSL_PIC -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -m64 -DL_ENDIAN -DTERMIO -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -Wl,-Bsymbolic-functions -Wl,-z,relro -Wa,--noexecstack -Wall -DMD32_REG_T=int -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DWHIRLPOOL_ASM -DGHASH_ASM
```

**Comment by nikefd** [comment]
I have the same problem, did you solve the problem ?

**Comment by km9173** [comment]
I have same error too...

**Comment by paradoxxxzero** [comment]
I don't understand, the error is clearly `http request` for an https server.
One way or another your browser is sending an http request instead of an https...
