### ISSUE TITLE
Butterfly start-up under Cygwin fails

### ISSUE THREAD

**Issue by gueleto** [paradoxxxzero/butterfly#98]
Launching both butterfly or butterfly.server.py fails with the following error

$ butterfly
No handlers could be found for logger "trollius"
Traceback (most recent call last):
  File "/usr/bin/butterfly.server.py", line 295, in <module>
    from butterfly import application
  File "/usr/lib/python2.7/site-packages/butterfly/__init__.py", line 72, in <module>
    import butterfly.routes
  File "/usr/lib/python2.7/site-packages/butterfly/routes.py", line 28, in <module>
    from butterfly import url, Route, utils, __version__
ImportError: cannot import name utils

In case this might be of any help "uname -a" prints out
CYGWIN_NT-6.1 gueleto-PC 2.4.0(0.293/5/3) 2016-01-15 16:14 i686 Cygwin 

Thank you very much for your help and assistance

**Comment by paradoxxxzero** [comment]
Duplicate #28
